apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elasticsearch-sink-connector
  labels:
    strimzi.io/cluster: kafka-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.elasticsearchindexsink.CamelElasticsearchindexsinkSinkConnector
  tasksMax: 1
  config:
    connector.class: org.apache.camel.kafkaconnector.elasticsearchindexsink.CamelElasticsearchindexsinkSinkConnector
    topics: "my-topic"
    tasks.max: "1"
    key.converter: org.apache.kafka.connect.storage.JsonConverter
    value.converter: org.apache.kafka.connect.storage.JsonConverter
    camel.kamelet.elasticsearch-index-sink.user: elastic
    camel.kamelet.elasticsearch-index-sink.password: 4zzQ1tW4VR049emXp1y8ee17
    camel.kamelet.elasticsearch-index-sink.enableSSL: true
    camel.kamelet.elasticsearch-index-sink.hostAddresses: kafka-elastic-es-http:9200
    camel.kamelet.elasticsearch-index-sink.clusterName: kafka-elastic
    camel.kamelet.elasticsearch-index-sink.indexName: kafka-sink



