apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kafka-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: mrs.ocir.io/axlykghcitkw/camel-kafkaconnect
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9093
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class:  org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: connector-config
        configMap:
          name: elastic-connector-config