apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: strimzi-kafka-bridge
  labels:
    app: strimzi-kafka-bridge-label
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.default:9092
  http:
    port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: strimzi-kafka-bridge-service
spec:
  type: NodePort
  selector:
    app: strimzi-kafka-bridge-label
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  